name: "Post  to Mattermost"
description: ""
branding:
  icon: send
  color: blue

inputs:
  mattermost_bot_token:
    description: "Mattermost bot token"
    required: true
  mattermost_channel_id:
    description: "Mattermost channel ID to post to"
    required: true
  mattermost_host:
    description: "Mattermost server host (e.g. mattermost.example.com)"
    required: true
  message: 
    description: "Message to send"
    required: true
  color: 
    description: "Color"
    required: false
    default: "#0000aa"



runs:
  using: "composite"
  steps:
    - name: Post Mattermost
      shell: bash
      env:
        MATTERMOST_BOT_TOKEN: ${{ inputs.mattermost_bot_token }}
        MATTERMOST_CHANNEL_ID: ${{ inputs.mattermost_channel_id }}
        MATTERMOST_HOST: ${{ inputs.mattermost_host }}
        MESSAGE: ${{ inputs.message }}
        COLOR: ${{ inputs.color }}
      run: |
        escaped="$(echo "$MESSAGE" | sed 's/"/\\"/g')"
        echo $escaped
        payload="{\"channel_id\":\"$MATTERMOST_CHANNEL_ID\",\"message\":\"Message from Github\", \"props\": {\"attachments\": [{ \"color\": \"$COLOR\", \"text\": "${escaped}"}]}}"
        echo $payload
        curl -X POST -H 'Content-Type: application/json' -H "Authorization: Bearer $MATTERMOST_BOT_TOKEN" -d "$payload" "https://$MATTERMOST_HOST/api/v4/posts"